#!/bin/sh

mkdir -p /proc /sys /dev /tmp
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true

echo "runix initramfs"
echo "Type 'poweroff -f' to exit."

exec /bin/sh
